### ISSUE TITLE
Specify dependecies version

### ISSUE THREAD

**Issue by arthurcvm** [itxtoledo/Stablecoins-Infinity-Profit-Bot#3]
Please, specify the version of NodeJS and NPM in readme.md to start aplication.

**Comment by Gab0** [comment]
I'm on `nodejs v11.15.0` and `npm 6.9.2`. Bot crashes on startup..

**Comment by arthurcvm** [comment]
I'm solve my problem in fresh release install of NodeJS and NPM in fresh Linux VM, but I can't identified the error reason.

**Comment by Gab0** [comment]
Oh, just found out my crash was due to port 80 already being used... Cool, you could have pasted the error log but nevermind if everything is fine now...

**Comment by arthurcvm** [comment]
I'm report in Telegram group, but don't had a solution.

**Comment by itxtoledo** [comment]
My node : v12.5.0, and npm: 6.9.0

**Comment by itxtoledo** [comment]
Added in readme 

[b6c2c94ab1518a3b5424c35f451b98f736629de2](https://github.com/itxtoledo/Stablecoins-Infinity-Profit-Bot/commit/b6c2c94ab1518a3b5424c35f451b98f736629de2)
